# Generated by Django 2.0.4 on 2018-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0003_image_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='image',
        ),
        migrations.AddField(
            model_name='userimage',
            name='caption',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userimage',
            name='img',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ForestSN.UserImage'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
