# Generated by Django 2.0.4 on 2018-05-24 06:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0005_auto_20180524_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 6, 16, 8, 267325, tzinfo=utc), verbose_name='publication date'),
            preserve_default=False,
        ),
    ]
