# Generated by Django 2.0.4 on 2018-05-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_post_set', to='ForestSN.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='root_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_post_set', to='ForestSN.Post'),
        ),
    ]
