# Generated by Django 2.0.4 on 2018-05-24 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ForestSN', '0008_auto_20180524_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='wall_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wall_owners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
