# Generated by Django 2.0.4 on 2018-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0009_auto_20180524_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publication date'),
        ),
    ]
