# Generated by Django 2.0.4 on 2018-06-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0010_auto_20180524_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ForestSN.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='root_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='ForestSN.Post'),
        ),
    ]
