# Generated by Django 2.0.6 on 2018-06-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0012_accesstoken_authorizationcode_externalsocialnetwork_externalsocialnetworksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='app_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
