# Generated by Django 2.0.6 on 2018-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0013_accesstoken_app_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='app_name',
            new_name='service',
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='service',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
