# Generated by Django 2.0.6 on 2018-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestSN', '0014_auto_20180608_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsocialnetworksession',
            name='ext_user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
